version: "3.8"

services:
  app:
    container_name: expense-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - META_TOKEN=${META_TOKEN}
      - META_PHONE_NUMBER_ID=${META_PHONE_NUMBER_ID}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN}
      - CRON_SECRET=${CRON_SECRET}
      - NODE_ENV=${NODE_ENV}
    command: yarn dev
    networks:
      - expense-tracker-network
    restart: unless-stopped

networks:
  expense-tracker-network:
    driver: bridge
